export const REACT_APP_TWITTER_CLIENT_ID="RUM2UElLcXFhWV9qLVlIZ1hyYzQ6MTpjaQ"
export const REACT_APP_TWITTER_CLIENT_SECRET="UUWPBOROgwKcQ8CB_UEnI81Hn-V0s7hloUL-W0CiD91DH0188a"
export const REACT_APP_REDIRECT_URI="http://localhost:3000/callback"
export const REACT_APP_BASE_API="your_api_base"
